# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Jonathan Giuffrida'
tagline:          'Adventures in Data Analysis and Bunnies'
description:      'I work at the intersection of quantitative analysis, healthcare, urban policy, and humanistic learning.'
url:              http://lucaluca.github.io
baseurl:          /
author:
  name:           'Jonathan Giuffrida'
  url:            http://lucaluca.github.io

paginate:         5  # 5 posts per page

# Custom vars
version:          0.1

github:
  repo:           https://github.com/lucaluca/lucaluca.github.io
