# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Alex Dumitriu'
tagline:          'Adventures in Public Policy and Bunnies'
description:      ''
url:              http://iadumitriu.github.io
baseurl:          /
author:
  name:           'Alex Dumitriu'
  url:            http://iadumitriu.github.io

paginate:         5  # 5 posts per page
paginate_path:    '/projects/page:num/'

# Custom vars
version:          0.1

github:
  repo:           https://github.com/iadumitriu/iadumitriu.github.io
